---
- name: Docker Swarm
  hosts: [ 'debops_docker_hosts' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  vars:
    swarm_status: "{{ hostvars[inventory_hostname]['docker_info']['Swarm']['LocalNodeState'] }}"

  tasks:
    # call library module docker_info_facts
    - name: load docker info as facts
      docker_info_facts:

    - debug: var=swarm_status

    # - debug:
    #     msg: "docker_info: {{ hostvars[inventory_hostname]['docker_info'] }}"

    # {
    #   u'ContainersPaused': 0,
    #   u'Labels': None,
    #   u'CgroupDriver': u'cgroupfs',
    #   u'ContainersRunning': 0,
    #   u'NGoroutines': 162,
    #   u'Swarm': {
    #     u'Managers': 1,
    #     u'ControlAvailable': True,
    #     u'NodeID': u'68wrp3a2dkf8ijfl764usxzc1',
    #     u'Cluster': {
    #       u'Spec': {
    #         u'Name': u'default',
    #         u'TaskDefaults': {},
    #         u'Orchestration': {u'TaskHistoryRetentionLimit': 5},
    #         u'Raft': {
    #           u'HeartbeatTick': 1,
    #           u'LogEntriesForSlowFollowers': 500,
    #           u'ElectionTick': 3,
    #           u'SnapshotInterval': 10000
    #         },
    #         u'CAConfig': {
    #           u'NodeCertExpiry': 7776000000000000
    #         },
    #         u'Dispatcher': {
    #           u'HeartbeatPeriod': 5000000000
    #         }
    #       },
    #       u'Version': {
    #         u'Index': 11
    #       },
    #       u'ID': u'3qr7ehsyy75astr3bjnm2boex',
    #       u'CreatedAt': u'2017-06-01T21:56:33.94551975Z',
    #       u'UpdatedAt': u'2017-06-01T21:56:33.961929555Z'
    #     },
    #     u'Nodes': 1,
    #     u'Error': u'',
    #     u'RemoteManagers': [
    #       {
    #         u'NodeID': u'68wrp3a2dkf8ijfl764usxzc1',
    #         u'Addr': u'10.0.2.15:2377'
    #       }
    #     ],
    #     u'LocalNodeState': u'active',
    #     u'NodeAddr': u'10.0.2.15'
    #   },
    #   u'LoggingDriver': u'json-file',
    #   u'OSType': u'linux',
    #   u'HttpProxy': u'',
    #   u'DriverStatus': [[u'Backing Filesystem', u'extfs']],
    #   u'OperatingSystem': u'Ubuntu 16.10',
    #   u'Containers': 0,
    #   u'HttpsProxy': u'',
    #   u'BridgeNfIp6tables': True,
    #   u'MemTotal': 1039937536,
    #   u'Driver': u'overlay',
    #   u'IndexServerAddress': u'https://index.docker.io/v1/',
    #   u'DefaultRuntime': u'runc',
    #   u'ExperimentalBuild': False,
    #   u'ExecutionDriver': u'',
    #   u'SystemStatus': None,
    #   u'OomKillDisable': True,
    #   u'ClusterAdvertise': u'',
    #   u'SystemTime': u'2017-06-01T22:51:22.24785517Z',
    #   u'Name': u'node01',
    #   u'CPUSet': True,
    #   u'RegistryConfig': {
    #     u'InsecureRegistryCIDRs': [u'127.0.0.0/8'],
    #     u'IndexConfigs': {
    #       u'docker.io': {
    #         u'Official': True,
    #         u'Name': u'docker.io',
    #         u'Secure': True,
    #         u'Mirrors': None
    #       }
    #     },
    #     u'Mirrors': None
    #   },
    #   u'SecurityOptions': [u'apparmor', u'seccomp'],
    #   u'ContainersStopped': 0,
    #   u'NCPU': 2,
    #   u'NFd': 36,
    #   u'Architecture': u'x86_64',
    #   u'KernelMemory': True,
    #   u'CpuCfsQuota': True,
    #   u'Debug': False,
    #   u'ID': u'DRU5:ULTJ:S5PV:TZV2:SHHL:U7EQ:AGKZ:SLGV:M46M:7NQQ:IBBJ:BL4C',
    #   u'IPv4Forwarding': True,
    #   u'KernelVersion': u'4.8.0-49-generic',
    #   u'BridgeNfIptables': True,
    #   u'NoProxy': u'',
    #   u'LiveRestoreEnabled': False,
    #   u'ServerVersion': u'1.12.6',
    #   u'CpuCfsPeriod': True,
    #   u'Runtimes': {
    #     u'runc': {
    #       u'path': u'runc'
    #     }
    #   },
    #   u'MemoryLimit': True,
    #   u'SwapLimit': False,
    #   u'ClusterStore': u'',
    #   u'Plugins': {
    #     u'Volume': [u'local'],
    #     u'Network': [u'null', u'host', u'bridge', u'overlay'],
    #     u'Authorization': None
    #   },
    #   u'Images': 0,
    #   u'DockerRootDir': u'/var/lib/docker',
    #   u'NEventsListener': 0,
    #   u'CPUShares': True
    # }

- include: docker_swarm_manager.yml

- include: docker_swarm_worker.yml
