- name: Docker Swarm Manager Operational
  hosts: [ 'swarm_manager_operational' ]
  become: True

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  tasks:

    - name: retrieve swarm manager token
      shell: docker swarm join-token -q manager
      register: swarm_manager_token

    - debug: var=swarm_manager_token

    - name: retrieve swarm worker token
      shell: docker swarm join-token -q worker
      register: swarm_worker_token

    - debug: var=swarm_worker_token

    - name: populate list of manager ips
      add_host:
        hostname: "{{ hostvars[item]['ansible_default_ipv4']['address'] }}"
        groups: swarm_manager_ips
      with_items: "{{ play_hosts }}"

    - debug: var=groups['swarm_manager_ips']


    # - debug:
    #     msg: "groups: {{ hostvars[inventory_hostname]['groups'] }}"

    # - debug:
    #     msg: "hostvars: {{ hostvars[inventory_hostname] }}"

