- name: Docker Swarm Worker
  hosts: [ 'swarm_workers' ]
  become: True

  #
  # check swarm status on each host
  # if swarm status is active add host to swarm_worker_operational hosts group
  # if swarm status is not active add host to swarm_worker_bootstrap hosts group
  #

  environment: '{{ inventory__environment | d({})
                   | combine(inventory__group_environment | d({}))
                   | combine(inventory__host_environment  | d({})) }}'

  vars:
    swarm_status: "{{ hostvars[inventory_hostname]['docker_info']['Swarm']['LocalNodeState'] }}"

  tasks:
    - debug: var=swarm_status

    - name: create swarm_worker_operational group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_worker_operational
      with_items: "{{ play_hosts }}"
      when: swarm_status == "active"
      run_once: true

    - debug: var=hostvars[inventory_hostname]['groups']['swarm_worker_operational']

    - name: create swarm_worker_bootstrap group
      add_host:
        hostname: "{{ item }}"
        groups: swarm_worker_bootstrap
      with_items: "{{ play_hosts }}"
      when: swarm_status != "active"
      run_once: true

    - debug: var=hostvars[inventory_hostname]['groups']['swarm_worker_bootstrap']

- include: docker_swarm_worker_bootstrap.yml

- include: docker_swarm_worker_operational.yml

